### ISSUE TITLE
getMessageStatus returns the following error

### ISSUE THREAD

**Issue by IbrahimTareq** [messagemedia/messages-java-sdk#5]
java.util.regex.PatternSyntaxException: Illegal repetition
{messageId}
               at java.util.regex.Pattern.error(Pattern.java:1957)
               at java.util.regex.Pattern.closure(Pattern.java:3159)
               at java.util.regex.Pattern.sequence(Pattern.java:2136)
               at java.util.regex.Pattern.expr(Pattern.java:1998)
               at java.util.regex.Pattern.compile(Pattern.java:1698)
               at java.util.regex.Pattern.<init>(Pattern.java:1351)
               at java.util.regex.Pattern.compile(Pattern.java:1028)
               at java.lang.String.replaceAll(String.java:2223)
               at com.messagemedia.messages.APIHelper.appendUrlWithTemplateParameters(APIHelper.java:232)
               at com.messagemedia.messages.controllers.MessagesController.getMessageStatusAsync(MessagesController.java:367)
               at com.messagemedia.messages.controllers.MessagesController.getMessageStatus(MessagesController.java:322)
               at com.messagemedia.messages.controllers.MessagesController.getMessageStatus(MessagesController.java:283)

**Comment by IbrahimTareq** [comment]
Identified the issue, The issue seems to be in line 364 of the getMessageStatusAsync method in the MessagesController. 

`String requestUri = "/v1/messages/{messageId}";` 

requestUri is supposed to be a StringBuilder not a String. Code seems to be working as expected after this change was made.

**Comment by IbrahimTareq** [comment]
Identified the bug. The issue seems to be in line 364 of the getMessageStatusAsync method in the MessagesController.

String requestUri = "/v1/messages/{messageId}";

requestUri is supposed to be a StringBuilder not a String. Code seems to be working as expected after this change was made.
